linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

run:
  skip-dirs:
    - vendor
    - test
    - docs

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck 