// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"

	onfleet "github.com/onfleet/cq-source-onfleet/internal/go-onfleet/onfleet"
	mock "github.com/stretchr/testify/mock"
)

// AdminServiceInterface is an autogenerated mock type for the AdminServiceInterface type
type AdminServiceInterface struct {
	mock.Mock
}

// List provides a mock function with given fields: ctx
func (_m *AdminServiceInterface) List(ctx context.Context) ([]onfleet.Admin, error) {
	ret := _m.Called(ctx)

	var r0 []onfleet.Admin
	if rf, ok := ret.Get(0).(func(context.Context) []onfleet.Admin); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]onfleet.Admin)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewAdminServiceInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewAdminServiceInterface creates a new instance of AdminServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAdminServiceInterface(t mockConstructorTestingTNewAdminServiceInterface) *AdminServiceInterface {
	mock := &AdminServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
