name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: false
      - name: Get dependencies
        run: |
          go env
          go mod download -x
          go mod tidy
          go list -m all
      - name: Build
        run: go build -v ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.1
          args: --timeout=3m --verbose
          skip-pkg-cache: true
          skip-build-cache: true
          working-directory: .
      - name: Setup CloudQuery
        if: github.event_name == 'pull_request'
        uses: cloudquery/setup-cloudquery@v3
        with:
          version: v3.28.1
      - name: Test
        run: make test
      - name: gen
        if: github.event_name == 'pull_request'
        run: make gen
      - name: Fail if generation updated files
        if: github.event_name == 'pull_request'
        run: test "$(git status -s | wc -l)" -eq 0 || (git status -s; exit 1)